### ISSUE TITLE
May I ask why this game lock china region on steam ?

### ISSUE THREAD

**Issue by Cooky-12** [jukibom/FlyDangerous#213]
Really a good open source game.

**Comment by jukibom** [comment]
Because the game has a [Taiwan flag](https://github.com/jukibom/FlyDangerous/blob/main/Assets/Textures/UI/Flags/tw.png) choice in the user profile so it has to be blocked, apparently. I could make an entirely separate build for China Which replaces that graphic but right now that's just super low priority (doing builds with and without steam integration across three platforms already takes hours to do v_v)

**Comment by Cooky-12** [comment]
> Because the game has a [Taiwan flag](https://github.com/jukibom/FlyDangerous/blob/main/Assets/Textures/UI/Flags/tw.png) choice in the user profile so it has to be blocked, apparently. I could make an entirely separate build for China Which replaces that graphic but right now that's just super low priority (doing builds with and without steam integration across three platforms already takes hours to do v_v)

I see. I not sure how to deal this, but may be you can add a little trick when game launch with china ip or system language is chinese, show something else not "Taiwan flag".

DDraceNetwork did this, I don't know the logic.

**Comment by jukibom** [comment]
Interesting, my understanding was that the actual image cannot be included in the build but I may be wrong about that
